// Generated by Haxe 3.4.0
(function () { "use strict";
var RecursionTest = function() { };
RecursionTest.factorialHelper = function(n,acc) {
	var __fresult;
	while(true) {
		var tmp;
		if(n > 0) {
			--n;
			acc *= n;
			tmp = true;
		} else {
			__fresult = acc;
			tmp = false;
		}
		if(!tmp) {
			break;
		}
	}
	return __fresult;
};
RecursionTest.factorial = function(n) {
	return RecursionTest.factorialHelper(n,1);
};
RecursionTest.main = function() {
	console.log("hello");
};
RecursionTest.__meta__ = { statics : { factorialHelper : { tailrecursive : null}}};
RecursionTest.main();
})();
